Insert into bookmarks(title,url,created_at)Values('how to code','http://sql.com',CURRENT_TIMESTAMP()),('how to code','http://sql.com',CURRENT_TIMESTAMP()),
('how to code1','http://sql.com',CURRENT_TIMESTAMP()),
('how to code2','http://sql.com',CURRENT_TIMESTAMP()),
('how to code3','http://sql.com',CURRENT_TIMESTAMP()),
('how to code4','http://sql.com',CURRENT_TIMESTAMP()),
('how to code5','http://sql.com',CURRENT_TIMESTAMP()),
('how to code6','http://sql.com',CURRENT_TIMESTAMP()),
('how to code7','http://sql.com',CURRENT_TIMESTAMP()),
('how to code8','http://sql.com',CURRENT_TIMESTAMP()),
('how to code9','http://sql.com',CURRENT_TIMESTAMP()),
('how to code10','http://sql.com',CURRENT_TIMESTAMP()),
('how to code11','http://sql.com',CURRENT_TIMESTAMP()),
('how to code12','http://sql.com',CURRENT_TIMESTAMP()),
('how to code13','http://sql.com',CURRENT_TIMESTAMP()),
('how to code14','http://sql.com',CURRENT_TIMESTAMP());
